### ISSUE TITLE
Reuse LoadBalancers (HTTP/S) when specifying multiple ports

### ISSUE THREAD

**Issue by sirdarckcat** [google/kctf#112]
HTTP/S load balancers support mapping through the hostname. We can map different hostnames to different HTTP ports. https://github.com/google/kctf/pull/101#discussion_r447668078

**Comment by sirdarckcat** [comment]
this is obsolete, the way we manage namespaces now varies per task.

**Comment by sroettger** [comment]
is there an advantage of reusing the load balancer? IIUC the price is per forwarding rule and not per load balancer, right?
