### ISSUE TITLE
kctf-config-load hides error in gcloud

### ISSUE THREAD

**Issue by sroettger** [google/kctf#127]
kctf-config-load will delete the old config from kubectl. This breaks if the newly loaded config is the same as the old

**Comment by sroettger** [comment]
actually, that's not what happened: I had to re-auth to gcloud. But the script was hiding the error and didn't create the config.

**Comment by sirdarckcat** [comment]
@sroettger is this still a problem? I think the new way to do this isn't prone to the same issue? https://github.com/google/kctf/blob/beta/dist/activate
