### ISSUE TITLE
Change the way we pass the difficulty of Proof of Work

### ISSUE THREAD

**Issue by aliciafmachado** [google/kctf#130]
With the operator, the way that we do it with a ConfigMap might be too much and unnecessary.
https://github.com/google/kctf/pull/128#pullrequestreview-475320237

**Comment by sroettger** [comment]
that would mean that we have to restart the task though in order to change the proof-of-work difficulty

**Comment by sirdarckcat** [comment]
passing it as a configmap is necessary for https://github.com/google/kctf/issues/119 as otherwise the difficulty wont be consistent across replicas

**Comment by sirdarckcat** [comment]
closing for now, but plz reopen if you want :)

 @gree-gorey
