### ISSUE TITLE
Add a walkthrough how to modify the chroot

### ISSUE THREAD

**Issue by sroettger** [google/kctf#141]
A common use case is to add a package to the chroot required by the challenge.
We should explain how to enable "universe" packages and how to install it.

**Comment by sirdarckcat** [comment]
if we get nsjail to do --exec_wrapper, we could just have people provide their own Dockerfile for the chroot, right?

**Comment by sroettger** [comment]
Yeah, that's correct. Currently, we just require the pow code to live in
the chroot.

**Comment by sirdarckcat** [comment]
this is done/obsolete now, I think.

**Comment by sroettger** [comment]
Yeah, modifying the chroot is now part of the examples / template and very easy to do.
