### ISSUE TITLE
Find a way to annotate images with challenge versioning information

### ISSUE THREAD

**Issue by sroettger** [google/kctf#143]
Let's say there's two admins that deploy challenges.
Admin A deployed challenge foo.
How does admin B check if foo is up to date with the latest changes in git?

You can just redeploy, but that is not ideal.

Timestamp of image creation/deployment also don't tell you since admin A's git might have been outdated.

Ideally, we would want to tag the deployment with the last git commit that affected the challenge or base image.

**Comment by sirdarckcat** [comment]
maybe we can build-in support for github? private repos are free now, so people could just run a workflow action or something like that

**Comment by sroettger** [comment]
You mean having the workflow push the image?
I don't like it, working with workflows is super slow and debugging them is
somewhat annoying.

**Comment by sirdarckcat** [comment]
yea, I mean, the admins not pushing things directly, but rather have another service do so. either github actions, or something else. as an author, you could just continuously push to head, which builds and pushes images. the admin then just has to select which images it wants the cluster can use.

**Comment by sroettger** [comment]
So right now you can at least check in the challenge.yaml with the updated image tag.
This allows you to check if the version running in the cluster is the same as the version in challenge.yaml.

Do we need anything else?

So for the example scenario in the first post:
> Let's say there's two admins that deploy challenges.
> Admin A deployed challenge foo.
> How does admin B check if foo is up to date with the latest changes in git?

If you deploy, you would always have to git push your challenge.yaml afterwards.
Admin B can then check the git history to find the image hash that is running on the cluster.

**Comment by sirdarckcat** [comment]
Checking in the challenge.yaml before performing an update solves this problem (it ensures that you always were HEAD at some point). And if you collide with another sysadmin, you'll get a merge error.

**Comment by sirdarckcat** [comment]
Closing since I think we are done here, but reopen otherwise
