### ISSUE TITLE
Get rid of $chaldir/kctf-conf/base ?

### ISSUE THREAD

**Issue by sroettger** [google/kctf#175]
At the moment we make a copy of base into the challenge directory, which includes the nsjail and healthcheck base images etc.

The original idea was that a CTF might want to make changes to these things that apply to the whole CTF. However with the operator, we already removed parts of these options, i.e. you can't change the deployment config etc anymore.

So this leaves:
* the challenge skeleton
* the nsjail base image
* the healthcheck bae image
* the Makefile

I don't think it's super useful that the challenge skeleton is stored there. If you would want to make changes to all challenges, you can actually just change all challenges with a bash for loop or so.

The nsjail and healthcheck images would be better if they were prebuilt by us instead of having everyone build them locally. I.e. in the latter case, they might differ between different challenge authors (apt-get update ran at different times).
And you can still make modifications to it by just creating your own image that is based on the nsjail image and in the challenges, change the FROM line to use your own base image instead.

Are there good reasons to modify the Makefile? I can't think of anything and modifying it will make upgrades hard.

**Comment by sroettger** [comment]
@sirdarckcat overall I think we should simplify this and get rid of the base folder.

**Comment by sirdarckcat** [comment]
is this done?

**Comment by sirdarckcat** [comment]
(I think now everything is on `/dist`)
