### ISSUE TITLE
Come up with a better idea for challenge/Makefile

### ISSUE THREAD

**Issue by sroettger** [google/kctf#177]
We ask task authors to provide a Makefile in their challenge directory with the target `.gen/docker-image`.

Maybe it would be a nicer interface to have players provide a bash script instead to build the challenge. Especially if the challenge doesn't need building or wants to use a different build system.

So it could just be a `build.sh` that prints the docker image and prints the id on stdout.

The infrastructure could also run `docker build` on the challenge directory if no `build.sh` exists. Is this too much magic?

**Comment by sirdarckcat** [comment]
this is done, right?

**Comment by sroettger** [comment]
for the record, we decided to only do docker build. build.sh is not needed since you should build in a docker container instead.
