### ISSUE TITLE
No monitoring data for challenge

### ISSUE THREAD

**Issue by sroettger** [google/kctf#178]
Looking at the details of a challenge deployment in the gce UI, it says "no data available" everywhere.
We might have blocked the data collection with our firewall rules.

**Comment by sirdarckcat** [comment]
This is #30 I think.

**Comment by sroettger** [comment]
I understood #30 as "we want better monitoring".
This one in particular is about fixing a bug that we don't collect any monitoring data at the moment. But it's fine to merge.

**Comment by sirdarckcat** [comment]
I see some here https://console.cloud.google.com/monitoring/dashboards/resourceList/kubernetes?organizationId=433637338589&project=kctf-github-ci-269714&pageState=(%22interval%22:(),%22gkeTableState%22:())

**Comment by sirdarckcat** [comment]
https://cloud.google.com/stackdriver/docs/solutions/gke/troubleshooting talks about service accounts possibly being the problem

**Comment by sirdarckcat** [comment]
@sroettger can you give me access to the project where you couldn't see any monitoring data?

**Comment by sirdarckcat** [comment]
![image](https://user-images.githubusercontent.com/33089/108213154-036feb00-712f-11eb-9213-8c11d24b035e.png)

**Comment by sirdarckcat** [comment]
plz reopen if there's anything missing, maybe this got fixed by itself (legacy monitoring?)

https://console.cloud.google.com/monitoring/dashboards/resourceList/kubernetes?orgonly=true&project=gctf-vrp
