### ISSUE TITLE
make it possible to create a cluster with just the command line

### ISSUE THREAD

**Issue by sirdarckcat** [google/kctf#19]
`kctf-config-create` requires user interaction, so it's hard to automate cluster configuration generation (we need to set some environment variables or generate the config manually).

Would be nice if we had a way to do this in a scriptable form.

**Comment by sroettger** [comment]
I don't understand this, can you add a description?

**Comment by sirdarckcat** [comment]
sure, done

**Comment by sroettger** [comment]
this is fixed by #43 right?

**Comment by sirdarckcat** [comment]
Yep, thanks!!
