### ISSUE TITLE
we cant reference the workload identity pool before we create the cluster

### ISSUE THREAD

**Issue by sirdarckcat** [google/kctf#193]
ERROR: Policy modification failed. For a binding with condition, run "gcloud alpha iam policies lint-condition" to identify issues in condition.
ERROR: (gcloud.iam.service-accounts.add-iam-policy-binding) INVALID_ARGUMENT: Identity Pool does not exist (sdcpocs1.svc.id.goog). Please check that you specified a valid resource name as returned in the `name` attribute in the configuration API.

**Comment by sroettger** [comment]
where do we reference it?

**Comment by sirdarckcat** [comment]
idk :) it works now. I think the tool was reusing an existing cluster

**Comment by sirdarckcat** [comment]
(I did `kctf cluster stop` and then start again, and it worked)
