### ISSUE TITLE
Dont create Service Accounts through the operator

### ISSUE THREAD

**Issue by sirdarckcat** [google/kctf#205]
The current situation is kindof suboptimal.
 1. The operator creates the KSA
 2. The operator launches a daemonset/deployment using KSAs

But the KSAs need to be annotated to point to the GSA (GSAs are not managed by operator, they are managed by the SDK as they are done with gcloud). This means that there's always a moment in which the KSA is not associated with a GSA, and that moment causes problems.

One solution to this problem is to create the GSAs ahead of time, and tell the operator to do the annotations itself. The sequence of events would be:
  1. Create cluster
  2. Create GSAs and add corresponding policy bindings
  2. Configure operator to use the correct GSAs
  3. Create operator

Alternatively, a simpler solution would just be to stop creating the KSAs in the operator, and instead manage those purely in the SDK. This is likely confusing, but probably less confusing than what we have at the moment.

See #201 for some symptoms of this problem.

---
KSA=Kubernetes Service Account
GSA=Google Service Account

**Comment by sroettger** [comment]
IMO, we should just move all the startup code out of the operator.
It would have been nice if you only had to install the operator and get a working kctf cluster, but that's not possible without giving the operator more gce permissions.

**Comment by sirdarckcat** [comment]
I'll try to move some things out and clean it up a bit.

I think we might not be able to fully remove the setup, because some of it is "internal" to the operator (like the pow secrets, network policy, etc), but we can start with https://github.com/google/kctf/blob/beta/kctf-operator/pkg/resources/service-accounts-sa.go

In the future we might wanna move all services (external-dns, certbot, gcsfuse) out of the operator and version them independently (say, with helm or something). But for now I think we can at least move the service accounts out, as they are the ones that have the weirdest setup.

**Comment by sroettger** [comment]
> some of it is "internal" to the operator (like the pow secrets, network policy, etc)

Can you expand on this? I don't see why we couldn't create them outside the operator.

**Comment by sirdarckcat** [comment]
if we move everything out, including all services, then we could yes.

but with what we have at the moment, we will end up splitting maintenance of resources in 2 places, which isnt gr8
