### ISSUE TITLE
Write new docs

### ISSUE THREAD

**Issue by sirdarckcat** [google/kctf#228]
1. Update cloudshell demo to use sdk
2. Update cloudshell demo to use kind
3. Add new step to cloudshell demo for gke
4. Make a 3 step quick start for landing
5. Update all other docs (threat model, etc)

**Comment by sirdarckcat** [comment]
SDK installation:
```bash
mkdir ctf-directory && cd ctf-directory
curl //kctf.dev/sdk_1_0_0 | tar xzf
source kctf/activate
```

3 step quick start:
```bash
kctf cluster create local-cluster --start --type kind
kctf chal create chal-sample && cd chal-sample
kctf chal start
```

**Comment by sroettger** [comment]
We can fix #237 with documentation

**Comment by sirdarckcat** [comment]
we can make kctf.dev links here https://firebase.corp.google.com/u/0/project/kctf-dev/durablelinks/creation/https:~2F~2Fkctf.dev

**Comment by sirdarckcat** [comment]
Installing the sdk:
```bash
curl -L https://github.com/google/kctf/releases/download/v1-test/kctf_0.0.1.tgz | tar -xz
```

**Comment by sirdarckcat** [comment]
Deps:
`apt install xxd wget curl`
https://docs.docker.com/engine/install/debian/#install-using-the-convenience-script

**Comment by sirdarckcat** [comment]
sudo sysctl -w kernel.unprivileged_userns_clone=1
https://superuser.com/questions/1094597/enable-user-namespaces-in-debian-kernel

**Comment by sirdarckcat** [comment]
`umask 022`

**Comment by sirdarckcat** [comment]
gcloud config.

**Comment by sirdarckcat** [comment]
so, I think we should have:
  1. quick start with kind. replacing https://github.com/google/kctf/blob/beta/docs/local-testing.md and this would be the main "walkthrough"
  2. deploying to the cloud. replacing https://github.com/google/kctf/blob/beta/docs/google-cloud.md

We need to update https://github.com/google/kctf/blob/beta/docs/troubleshooting.md as that still references alpha commands.
