### ISSUE TITLE
Document healthcheck

### ISSUE THREAD

**Issue by sroettger** [google/kctf#234]
If you create a new challenge it will work, but as soon as you change something in the challenge it starts failing since the healthcheck doesn't work anymore.

We should:
* have a nice user experience for this. Maybe have the healthcheck disabled by default in the templates?
* have good documentation for the healthcheck, maybe a README under the healthcheck folder

**Comment by sroettger** [comment]
we should be able to just simplify it:
doit.py can have a different name
env can go away
healthz.py could have something about "webserver" in the name
run.sh could say "healthcheckloop.sh" or so

**Comment by sirdarckcat** [comment]
this is done, right?

**Comment by sroettger** [comment]
Yes
