### ISSUE TITLE
Find a way to skip pow from healthcheck

### ISSUE THREAD

**Issue by sirdarckcat** [google/kctf#24]
The old trick
https://github.com/google/kctf/blob/ffcaec5bc5322955be7ecb3a8b105add4752b03f/base/nsjail-docker/files/proof_of_work/pow.py#L28
```python
def stdin_is_localhost_socket():
    try:
        sock = socket.socket(fileno=sys.stdin.fileno())
        peername = sock.getpeername()
        sock.detach()
        return peername[0] == '::ffff:127.0.0.1'
    except OSError:
        return False
```

Doesn't work anymore
https://github.com/google/nsjail/commit/273ce6bc846b7325c7f0915067c54bf8cf6f5654

**Comment by sroettger** [comment]
fixed with #40
