### ISSUE TITLE
Do an end-to-end test with a new project

### ISSUE THREAD

**Issue by sroettger** [google/kctf#246]
Make sure that the chal create doesn't block on any errors/questions.
Also that all APIs are enabled etc.

**Comment by sirdarckcat** [comment]
I tested on kind, and found some issues I left on #228 for docs.
We should test with gcloud too, but those probably can also be fixed with docs for #228.

**Comment by sroettger** [comment]
Working on the end to end test from a new project now.
Some notes on the steps:
* created an ubuntu 20.04 vm in GCE and deleted the google-cloud-sdk snap that came with it
* Opened the docs at https://google.github.io/kctf/ and started with local testing
* docker install, works
* downloading kctf etc instructions outdated as expected
* mkdir e2e, curl kctf | tar && cd e2e
* source kctf/activate
* kctf cluster create --type kind --start local
* kctf chal create --template pwn chal1 && cd chal1
* kctf chal start
* kctf chal status
* kctf chal debug port-forward
* nc 0 PORT
* kctf cluster stop

Then on GCP:
* create a project in pantheon
* try to run kctf cluster create --project <tab> => prints "gcloud not installed in autocomplete"
* kctf cluster create --project tmp-12317236178263 --domain-name tmp-12317236178263.kctf.cloud gcptest
  * prints warning "configuration created only locally, gcloud not installed"
* sudo snap install --classic google-cloud-sdk (--classic means it uses no sandboxing)
* kctf cluster start
  * ERROR: (gcloud.compute.networks.list) Some requests did not succeed:
     - Insufficient Permission: Request had insufficient authentication scopes.
* gcloud auth login
  * ERROR: (gcloud.auth.login) Cannot set property in configuration [kctf-6fb733c3c45c462b35c7], it does not exist.
* deactivate
* source kctf/activate
* gcloud auth login
  * You are now logged in
* kctf cluster start
  * [E] No cluster config loaded
* confusing: $(_kctf_config_string) returns ,config=gcptest
  * need to unset KCTF_CONFIG (also CHALLENGE_NAMESPACE, CHALLENGE_NAME, CHALLENGE_DIR) on deactivate
* loading .lastconfig fails silently => problem: required gcloud container cluster get credentials
* kctf cluster start
  * - Insufficient Permission: Request had insufficient authentication scopes.
* deactivate, gcloud auth login, source kctf/activate
  * blocked until I pressed enter, no idea what it was blocked on
* kctf cluster start
  * API [compute.googleapis.com] not enabled on project [1035128044679]. (would you like to retry?)
  * ERROR: (gcloud.container.clusters.create) ResponseError: code=400, message=Failed precondition when calling the ServiceConsumerManager: tenantmanager::185014: Consumer 1035128044679 should enable service:container.googleapis.com before generating a service account.
* gcloud services enable compute container containerregistry.googleapis.com && gcloud services enable compute container compute.googleapis.com && gcloud services enable compute container container.googleapis.com (from the docs)
* kctf cluster start
  * API [dns.googleapis.com] not enabled on project [1035128044679]. (retry?)
* cd chal1; kctf chal start
  * unauthorized: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication
* gcloud auth configure-docker
* kctf chal start
* kctf chal debug port-forward & nc 0 PORT

**Comment by sroettger** [comment]
The issues from above:
- [x] it's ok to create the gcp config without gcloud, but it should not get activated
- [x] need to unset KCTF_CONFIG, CHALLENGE_NAMESPACE, CHALLENGE_NAME, CHALLENGE_DIR on deactivate
- [x] fix loading a config that doesn't have a cluster running
- [x] we can warn earlier if one of the APIs is not actiaveted (especially container.googleapis.com, which makes it fail instead of asking)
- [ ] make sure that we recommend `gcloud auth login` and `gcloud auth configure-docker` in the docs (we might already, I didn't really follow the docs). However, the error about missing gcloud auth configure-docker was actionable (the url tells you to run that)

**Comment by sroettger** [comment]
- [x] gcloud is broken in the kctf shell if you don't create/load a gcloud config since we set CLOUDSDK_ACTIVE_CONFIG_NAME= without creating the config. This means gcloud auth login fails if you haven't created the config yet.

**Comment by sirdarckcat** [comment]
I just did this again from cloud shell.

no issues

**Comment by sroettger** [comment]
Awesome
