### ISSUE TITLE
logs should also show the logs of the latest challenge, like ssh

### ISSUE THREAD

**Issue by sirdarckcat** [google/kctf#262]
same for port-forward

**Comment by sroettger** [comment]
Logs should already show all logs

**Comment by sirdarckcat** [comment]
when following the docs, it only showed the docs for the last one.

**Comment by sroettger** [comment]
Hmm, then I misunderstood the kubectl help:

```sh
  # Return snapshot logs from all containers in pods defined by label app=nginx
  kubectl logs -lapp=nginx --all-containers=true
```

This sounded like it would get logs from all pods with the label, but I guess it doesn't really say that.

**Comment by sirdarckcat** [comment]
oh, I meant our docs =P
