### ISSUE TITLE
Remove gcp issued certificate

### ISSUE THREAD

**Issue by sroettger** [google/kctf#283]
We currently set a wildcard cert in the loadbalancer and also let it acquire one itself.
However, that means the load balancer waits for the cert to be issued before serving the challenge.

**Comment by sirdarckcat** [comment]
it comes from here:
https://github.com/google/kctf/blob/ad029ed1c3e9c34d57761132fd5a5a53511dc4db/kctf-operator/pkg/controller/challenge/dns/functions.go#L48

We could delete it if the user decided not to use LetsEncrypt

**Comment by sirdarckcat** [comment]
oh.. we always create one now.
https://github.com/google/kctf/blob/ad029ed1c3e9c34d57761132fd5a5a53511dc4db/docker-images/certbot/certbot.sh

so I guess we can just remove this then
