### ISSUE TITLE
RBAC support

### ISSUE THREAD

**Issue by sirdarckcat** [google/kctf#29]
https://kubernetes.io/docs/reference/access-authn-authz/rbac/

**Comment by sirdarckcat** [comment]
this is already kindof supported in beta (I can give you access to modify "challenge" resources without giving you access to create pods/deployments directly)

the security isolation here isn't really strong, though, because the challenge can just define itself privileged, which I think is probably necessary :(

**Comment by sroettger** [comment]
> which I think is probably necessary :(

This should change though once the support for clean proc made it to stable k8s
