### ISSUE TITLE
Move Apache and Chrome to packages/cached containers

### ISSUE THREAD

**Issue by sirdarckcat** [google/kctf#34]
Takes a while to install, we probably can move them too (like pwntools, chroot, nsjail, etc)

**Comment by sirdarckcat** [comment]
@sroettger wdyt? this is an old issue, but for can we easily detect when we only made changes that wouldn't affect the samples? I don't know if this will really help (do we make a lot of changes here?)

or can we cache other steps?

**Comment by sroettger** [comment]
For testing or production? For the latter, we should try to recreate the images everytime. I.e. if I make a challenge that ships Chrome, I want to use the latest version from apt-get.

**Comment by sirdarckcat** [comment]
ok, then closing this. (it was for prod)
