### ISSUE TITLE
DNS Record Deletion - Does Not Exist

### ISSUE THREAD

**Issue by jordanbertasso** [google/kctf#340]
Hi,

Whilst following the Google Cloudshell Codelab tutorial with a brand new project, I encounter the following issue whilst creating a new ctf cluster.
```
ERROR: (gcloud.dns.record-sets.transaction.remove) Record to be removed does not exist
```

I've tried again on a new project and receive the same error.

The command I used to create the cluster was:
```
kctf cluster create --project \
    test-kctf-2 --domain-name \
    test-kctf-2-codelab.kctf.cloud \
    --start remote-cluster
```

I sort of managed to get around this the first time by editing transaction.yaml and removing the deletions section.
However, I experienced some issues while trying to access a web challenge after I continued with that setup which is why I created a new project to try again.

Let me know if you need any more information.

Thanks and awesome work on the project!

**Comment by sroettger** [comment]
Thanks for the report, looks like the data returned by gcloud might have changed. #341 should fix it.
