### ISSUE TITLE
kctf-operator stuck in shutdown leads to stuck deployments

### ISSUE THREAD

**Issue by sampritipanda** [google/kctf#343]
If we have a existing kctf-operator instance that is in shutdown, it does not release the lock on the operator. 

Code Reference: https://github.com/google/kctf/blob/v1/kctf-operator/cmd/manager/main.go#L143

As a result, the new operator instance is stuck waiting for this lock to be released. So, if we are stuck in this state and we make any changes to the deployments, they don't get deployed to the kctf cluster.

Example:
```
{"level":"info","ts":1633226662.943512,"logger":"leader","msg":"Found existing lock","LockOwner":"kctf-operator-895969847-r449c"}
```

To fix this, I had to manually delete the existing operator pods in shutdown using `kubectl delete pod kctf-operator-<xxx>`.

Ideally, if a operator is going to shutdown, it should release the lock to let the new one take over.

**Comment by sroettger** [comment]
just noticed we have that exact issue in our CI cluster :)

**Comment by sroettger** [comment]
Sounds like a problem with preemtible nodes:
https://stackoverflow.com/questions/68687716/k8s-pods-stuck-in-failed-shutdown-state-after-preemption-gke-v1-20

Maybe a leased lock would help. It can be created by using manager options like this:
```
  opts := manager.Options{
    ...
    LeaderElection: true,
    LeaderElectionID: "lockname"
  }
  mgr, err := manager.New(cfg, opts)
```

**Comment by sirdarckcat** [comment]
@sroettger where do we need to put that? on the operator?

**Comment by sroettger** [comment]
yes, but it looks like we're already doing that:
https://github.com/google/kctf/blob/v1/kctf-operator/main.go#L79 has
```
	mgr, err := ctrl.NewManager(ctrl.GetConfigOrDie(), ctrl.Options{
		Scheme:                 scheme,
		MetricsBindAddress:     metricsAddr,
		Port:                   9443,
		HealthProbeBindAddress: probeAddr,
		LeaderElection:         enableLeaderElection,
		LeaderElectionID:       "558d99b6.dev",
		Namespace:              "",
	})
```

**Comment by sirdarckcat** [comment]
oh, maybe this got fixed on the migration to the new operator version?
