### ISSUE TITLE
Cannot create security policy in google cloud

### ISSUE THREAD

**Issue by tomadimitrie** [google/kctf#350]
Hi, I am trying to use kctf in gce and the script fails at the security policy creation. The quota is 0 for some reason. Do you have any idea what to do? Thanks!

**Comment by sirdarckcat** [comment]
Could you request a quota increase? I'm not sure why there's a quota for this.

**Comment by tomadimitrie** [comment]
I can't, the button is greyed out

**Comment by sirdarckcat** [comment]
Do you have billing enabled? Are all quotas disabled or only that one

**Comment by tomadimitrie** [comment]
Billing is enabled, security policies are the only ones with 0 quota

**Comment by sirdarckcat** [comment]
One last thing! Can you check which zone/region you are using and if other
zones/regions have available quotas?

We'll look into why this is happening and consider other options

**Comment by tomadimitrie** [comment]
There wasn't a specific region set for compute engine, but I tried setting it and the quota is still 0. Is there any workaround? I also tried commenting out the create_cloud_armor_policy call, but the external ip is not accessible

**Comment by sirdarckcat** [comment]
@sroettger wdyt? is downgrading to the version before we added support for ip ranges be the easiest?

**Comment by sirdarckcat** [comment]
https://github.com/google/kctf/releases/tag/v1.1.0 added support for this, so 1.0.8 would be the best one - note we didn't backport all patches on 1.1 to 1.0

**Comment by tomadimitrie** [comment]
@sirdarckcat thank you for your answer! If I downgrade to that tag, which features will I miss (except the security policy)?

**Comment by sirdarckcat** [comment]
We tried to do semver so 1.1 was the first feature we added. You mostly might miss patches to bugs. Take a look at the releases here on GitHub to see.

**Comment by sirdarckcat** [comment]
Sorry, semver=https://semver.org/

**Comment by tomadimitrie** [comment]
Thank you so much for your help! :)

**Comment by sirdarckcat** [comment]
https://github.com/google/kctf/releases/tag/v1.5.0
