### ISSUE TITLE
Is there any way to get the status of all challenges in a cluster?

### ISSUE THREAD

**Issue by tomadimitrie** [google/kctf#352]
I know I can do `kctf chal status` for each challenge, but I was wondering if there is any way to get a list of all challenges' status

**Comment by sroettger** [comment]
You can use kubectl for this:
`kubectl get challenges` and/or `kubectl get pods` / `kubectl get deployments`.
Alternatively, the web UI should also have some nice overview to watch the challenge status somewhere at https://console.cloud.google.com

**Comment by tomadimitrie** [comment]
perfect, thank you so much!
