### ISSUE TITLE
Build tasks in parallel

### ISSUE THREAD

**Issue by sirdarckcat** [google/kctf#42]
Since we now remotely cache the most common parts of the Docker images, perhaps we can now parallelize the build.

This seems to imply finding a way of running make in parallel:

https://github.com/google/kctf/blob/c8783921d8a496e9f5ab0d0f591b158c461615ce/scripts/challenge/batch-deploy.sh#L44

Note that since `make start` might also touch things outside it's own directory (../kctf-conf/base), we currently can't just add a `&`.

We probably need to somehow separate the Makefile so we isolate all the task-specific build steps.

**Comment by sroettger** [comment]
we could run the make base/docker manually once, but it's not nice since we will need to remember to do this for newly introduced dependencies as well.
We should also add a "-j" to the make for a start. I thought it had that already.

**Comment by sirdarckcat** [comment]
we don't have ctf-wide tasks anymore, and we don't have makefiles anymore, so this is now obsolete (in other words, it's fixed)
