### ISSUE TITLE
Make it easier to create new Docker images in the same challenge

### ISSUE THREAD

**Issue by sroettger** [google/kctf#44]
Adding a new cached docker image is currently very finicky since you have to touch multiple files.
This should be easy to avoid by automating the push etc to automatically handle all subdirectories of config/docker.

I.e. ideally I would just create a new file in config/docker/my-image/Dockerfile, and the tooling would create the image gcr.io/../kctf-my-image for me.
This should work with a for dir in config/docker/* loop.

**Comment by sirdarckcat** [comment]
https://github.com/google/kctf/issues/157

**Comment by sirdarckcat** [comment]
https://github.com/google/kctf/issues/8

**Comment by sroettger** [comment]
This changed a bit since the time I opened this issue. You now have to do two things to create a new cached image:
1) create a subdirectory and add your Dockerfile etc\
2) update the .github/workflow to also build the image

I don't think we can do better than that in the current setup. Closing this issue.
