### ISSUE TITLE
Automatically pull latest images from gcr.io

### ISSUE THREAD

**Issue by sroettger** [google/kctf#56]
The apache-php example didn't build on my machine since gcr.io/kctf-docker/kctf-nsjail-chroot:latest was outdated.
We should always try to fetch the newest images from gcr.io during the build process, at least when creating the challenge directory.
Or alternatively hardcode the versions and update them when they change.

**Comment by sirdarckcat** [comment]
I think we'll be using versions once we start doing releases, so then this won't be an issue?

**Comment by sirdarckcat** [comment]
@sroettger is this done? `Or alternatively hardcode the versions and update them when they change.`

**Comment by sirdarckcat** [comment]
(I think the answer is yes, plz reopen if not)
