### ISSUE TITLE
GCS bucket ACLs for uniform access-control

### ISSUE THREAD

**Issue by gree-gorey** [google/kctf#74]
`gsutil acl ch -u "${GSA_EMAIL}:O" "gs://${BUCKET_NAME}"` from `scripts/cluster/start.sh` is only working with Fine-grained access-control. If Uniform access-control enabled for bucket, this needs to be changed for:
```
gsutil iam ch serviceAccount:${GSA_EMAIL}:roles/storage.legacyBucketOwner gs://${BUCKET_NAME}/
```
Probably need to add check before choosing the command.

**Comment by gree-gorey** [comment]
And also `legacyObjectOwner`:
```
gsutil iam ch serviceAccount:${GSA_EMAIL}:roles/storage.legacyObjectOwner gs://${BUCKET_NAME}/
```

**Comment by sirdarckcat** [comment]
Oh, I think last time I only added Bucket owner, and didn't add Object owner.. hmm.. :-)

Nice catch!

**Comment by gree-gorey** [comment]
Thanks :) Yes, the bucket owner has all the permissions except reading objects, I had to learn it myself the hard way :(

**Comment by sirdarckcat** [comment]
Sweet!
