### ISSUE TITLE
create a namespace per challenge, allow challenges to share a namespace

### ISSUE THREAD

**Issue by sirdarckcat** [google/kctf#8]

**Comment by sroettger** [comment]
@sirdarckcat should we close this? We now have a namespace per challenge. Do we still want the ability to have multiple challenges in the same namespace?

**Comment by sirdarckcat** [comment]
I guess it depends on whether we expect multi-stage tasks to share things. What's the solution for that? Multiple containers?

**Comment by sirdarckcat** [comment]
to answer my last question, the answer is yes, multiple containers
